window.data = {
  auth: {
    user: {
      name: "Pheobe Buffey",
      address: "princessconsuellahammock@gmail.com",
      followers: "500",
      following: "110",
      avatar: "/images/avatar/pheobe.jpg",
    },
    trends: [
      { name: "StrangerThings", posts: "756k" },
      { name: "TheMoneyHeist", posts: "546k" },
      { name: "Friends", posts: "501k" },
      { name: "TheBigBangTheory", posts: "324k" },
      { name: "VampireDaires", posts: "125k" },
    ],
    suggestions: [
      {
        name: "Monica",
        address: "Geller",
        avatar: "/images/avatar/monica.jpg",
      },
      { name: "Ross", address: "Geller", avatar: "/images/avatar/ross.jpg" },
      {
        name: "Chandler",
        address: "Bing",
        avatar: "/images/avatar/chandler.jpg",
      },
      { name: "Joey", address: "Tribbiani", avatar: "/images/avatar/joey.jpg" },
      { name: "Rachel", address: "green", avatar: "/images/avatar/rachel.jpg" },
    ],
  },
  posts: [
    {
      name: "Riya Shah",
      avatar: "/images/avatar/baruto.jpg",
      address: "riyaShah@hotmail.com",
      time: "23h",
      text: "I am Speechless & Overwhelmed. No amount of words can describe the emotions i felt today. This is one of the greatest fan service I've ever witnessed. And thus marks one of the greatest MCU movie ever made. What they pulled off is nothing sort of mind blowing and commendable. Hats off to everyone involved and for making this dream a reality.",
      images: ["/images/uploads/spider-man.jpg"],
      comments: 20,
      repost: 10,
      favorites: 50,
    },
    {
      name: "Sasuke Uchiha",
      avatar: "/images/avatar/sasuke.jpg",
      address: "SasukeUchiha",
      time: "3d",
      text: "It's advertising was scaress I saw it yesterday first 30mins I almost fell asleep I understood all the themes, I agree the fighting scenes were on point but not memorable, the flash backs annoying almost had a documentary feel to them I believe the intent effectively was more concentrated on the audience reaction which the others weren't so dominate in trying to achieve which was more value, with iconic characters moments and memories.. I am not taking much away from this addition the fact that trinity got the mojo this time scored with me and Keanu and Carrie still had that spark I liked it. But pushing the AI diversity was too predicable, I won't be buying the movie toys,  as it was plain to see. That agenda $$, placing sell point in films is like encouraging advertising at half time at the super bowl a yawn    Reality is story is good minus all the make do Hollywood humor antidotes which again like Thor went all giggly...I finish with this .. deja Vu who got the mumbo Jumbo boom lay  hoo doo",
      images: ["/images/uploads/matrix4.jpg"],
      comments: 20,
      repost: 10,
      favorites: 50,
    },
    {
      name: "Jake Parelta",
      avatar: "/images/avatar/gaara.jpg",
      address: "KazekageGaara",
      time: "3d",
      text: "I am thrilled to say the second half of the season from episode 10/11 on really picked up and totally has me hooked! Mild spoilers - They thankfully did damage control with Grace and her relationship with Ben and their family unit is back on track (for now), they introduced 2 new characters that drastically changed and further developed the whole scope and direction of the narrative (for the better), and they introduced a mind-blowing fact about everyone’s ultimate fate that will be the underlying force driving each season going forward. I’m totally intrigued by what they’re doing and can’t wait to see how it unfolds in Season 2 (which I hope and assume there will be based on the overall ratings and momentum). Just wish it weren’t 7 months away!!! (On a side note, its mid-season replacement “The Enemy Within”, looks really good and like it could be a big hit itself. Excited for that one to start up and help the months go by while awaiting S2 of Manifest!)",
      images: ["/images/uploads/manifest.jpeg"],
      comments: 20,
      repost: 10,
      favorites: 50,
    },
    {
      name: "Ishan Sharma",
      avatar: "/images/avatar/kakashi.jpg",
      address: "KakashiHatake",
      time: "12h",
      text: ' "Kabhi kabhi kuchh baten hamare yaadon ke kamre ki itni khirkiya khol dete Hain ki hum dang rhe jaate Hain." "Yaadein mithai ke dabbe ki tarah hota hai ek bar kholo to sirf ek tukda nahin kha paaoge."This is one of my favorite movies . I can not extoll how good this movie is... The movie is completely explain about Love , one-sided love , family issue , friendships , life , economy etc... Personally i recommend to everyone to watch this , especially for the one who is sad or depressed should definitely watch this movie .... Hope this movie is blessing for those who wish to fly , wish to run , wish to fall down just don not want to brake. For those who wants to live every single breath of their life . And the location were awesome (Manali & jaypur, Rajasthan) and all the songs are very beautiful, u can feel them.this has drama, comdey, best dialogues  n lots of emotions and many others things ... Deepika Padukone , Ranbir Kapoor , kalki koechlin & Aditya Roy Kapoor were like real character . it teaches us we get one life so enjoy do everything what u want do... There is my favorite line of Naina "jitna bhi try karo, kuch na kuch to chootega hi. isliye yahan isi pal ka hi maza lete hain"',
      images: ["/images/uploads/yjhd.jpg"],
      comments: 20,
      repost: 10,
      favorites: 50,
    },
  ],
};
